# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x' # Specify your Node.js version here
          cache: 'npm'

      - name: Install Dependencies
        run: |
          cd app
          npm install

      - name: Lint Code
        run: |
          cd app
          npm run lint
        # Ensure you have a lint script in your package.json

      - name: Run Tests
        run: |
          cd app
          npm run test
        # Ensure you have a test script in your package.json

      - name: Build Project
        run: |
          cd app
          npm run build

      - name: Generate Static Files
        run: |
          cd app
          npm run generate

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
          publish_branch: gh-pages
