# .github/workflows/deploy.yml

name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.2.0' # Specify your Node.js version here
          cache: 'none' # Disable default npm caching

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: app/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: |
          npm install
        working-directory: app

      - name: Lint Code
        run: |
          npm run lint
        working-directory: app
        # Ensure you have a lint script in your package.json

      - name: Run Tests
        run: |
          npm run test
        working-directory: app
        # Ensure you have a test script in your package.json

      - name: Build Project
        run: |
          npm run build
        working-directory: app

      - name: Generate Static Files
        run: |
          npm run generate
        working-directory: app

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/dist
          publish_branch: gh-pages
